version: "3"
services:
  load-balancer:
    build: ./lb
    links:
      - api
    volumes:
      - ./lb/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - 80:80
  api:
    build: ./app
  #  links:
  #    - db
  #  ports:
  #    - "5000:5000"
  #db:
  #  image: mysql:5.7
  #  ports:
  #    - "32000:3306"
  #  environment:
  #    MYSQL_ROOT_PASSWORD: root
  #  volumes:
  #    - ./db:/docker-entrypoint-initdb.d/:ro
